inherit_from: rubocop-todo.yml

#- CocoaPods -----------------------------------------------------------------#

# We adopted raise instead of fail.
SignalException:
  EnforcedStyle: only_raise

# These are idiomatic
AssignmentInCondition:
  Enabled: false

# Allow backticks
AsciiComments:
  Enabled: false

# Indentation clarifies logic branches in implementations
IfUnlessModifier:
  Enabled: false

# No enforced convention here.
SingleLineBlockParams:
  Enabled: false

# These are idiomatic
FormatString:
  Enabled: false

# Having these make it easier to *not* forget to add one when adding a new
# value and you can simply copy the previous line.
TrailingComma:
  Enabled: false

#- CocoaPods support for Ruby 1.8.7 ------------------------------------------#

HashSyntax:
  EnforcedStyle: hash_rockets

Lambda:
  Enabled: false


#- CocoaPods specs -----------------------------------------------------------#

# Allow for `should.match /regexp/`.
AmbiguousRegexpLiteral:
  Exclude:
    - spec/**/*

# Allow `object.should == object` syntax.
Void:
  Exclude:
    - spec/**/*

ClassAndModuleChildren:
  Exclude:
    - spec/**/*

#- Trunk ---------------------------------------------------------------------#

ClassVars:
  Exclude:
    - spec/**/*

MultilineBlockChain:
  Exclude:
    - spec/**/*

# Variables are used for the erb templates
UselessAssignment:
  Enabled: false

HandleExceptions:
  Exclude:
    - db/seeds.rb

FileName:
  Exclude:
    - spec/fixtures/**/*

LineLength:
  Exclude:
    - design/prototype/github.rb

# Sinatra app classes can be longer
ClassLength:
  Enabled: false

UnusedMethodArgument:
  Exclude:
    - db/seeds.rb
    - db/seeds/**/*
